services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_PASSWORD=rootpass'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    volumes:
      - 'pgadmin:/var/lib/pgadmin'

volumes:
  data:
  pgadmin:
